project_id = "kmuoqkcxguafxulqlbmi"

[project]
name = "imperial-trading"

[api]
enabled = true

[auth]
enabled = true

[edge_functions]
enabled = true

[functions.tradermade-streaming]
verify_jwt = false

[functions.enhanced-websocket-streaming]
verify_jwt = false

[functions.websocket-load-balancer]
verify_jwt = false

[functions.financial-websocket-optimized]
verify_jwt = false


[functions.check-user-existence]
verify_jwt = false

[functions.order-trigger-monitor]
verify_jwt = true

[functions.hello]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.reset]
verify_jwt = false
