project_id = "kmuoqkcxguafxulqlbmi"

[project]
name = "imperial-trading"

[api]
enabled = true

[auth]
enabled = true

[edge_functions]
enabled = true

[functions.price-ingestor]
verify_jwt = false

[functions.enhanced-alert-monitor]
verify_jwt = false

[functions.enhanced-signal-notification-dispatcher]
verify_jwt = false

[functions.cleanup-old-data]
verify_jwt = false

[functions.check-user-existence]
verify_jwt = false

[functions.password-reset]
verify_jwt = false
